language: node_js
node_js:
  - "10"
  - "8"
  - "6"
before_install:
  - yarn add stripe@^6.0.0 --no-save
script:
  - yarn test-coverage
after_script:
  - yarn add coveralls@^3.0.0 && cat ./coverage/lcov.info | coveralls
