language: node_js
node_js:
  - "10"
  - "8"
  - "6"
install:
  - npm i
  - npm i coveralls@^3.0.0
  - npm i stripe@^6.0.0
script:
  - npm run test-coverage
after_script:
  - cat ./coverage/lcov.info | coveralls
