language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "node"
sudo: false
before_script:
  - npm i stripe@^4.0.0
script:
  - npm run test-ci
after_script:
  - npm install coveralls@^2.0.0 && cat ./coverage/lcov.info | coveralls