language: node_js
node_js:
  - "10"
  - "8"
  - "6"
before_install:
  - npm i stripe@^6.0.0
script:
  - npm run test-coverage
after_script:
  - npm install coveralls@^3.0.0 && cat ./coverage/lcov.info | coveralls
