language: node_js
node_js:
  - "8"
  - "6"
  - "4"
before_install:
  - npm i stripe@^5.0.0
script:
  - npm run lint
  - npm run test-coverage
after_script:
  - npm install coveralls@^3.0.0 && cat ./coverage/lcov.info | coveralls
